CatorDog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vote.urls')),
]

vote/urls.py
from django.urls import path

from . import views

app_name = 'vote'

urlpatterns = [
    path('', views.home, name='home'),
    path('vote/<int:question_id>/', views.vote, name= 'vote'),
    path('results/<int:question_id>/', views.results, name= 'results'),
    path('resultsdata/<str:obj>/', views.resultsData, name= 'resultsdata'),
]

vote/models.py
"""Voting Model for Cat or Dog site"""

import datetime
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

vote/views.py
"""View to show the vote for Cat or Dog"""

from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse

# Create your views here.
from .models import Question, Choice

def home(request):
    """Only look at the last 10 questions"""
    questions = Question.objects.order_by('-pub_date')[:10]
    context = {'questions': questions}
    return render(request, 'vote/home.html', context)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        vote_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        """redirect to the page"""
        return render(request, 'vote/vote.html', {
        'question': question,
        })
    else:
        vote_choice.votes += 1
        vote_choice.save()
        return redirect('vote:results', question.id)


def results(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'vote/results.html', context)

def resultsData(request, obj):
    vote_info = []
    question = Question.objects.get(id=obj)
    choice = question.choice_set.all()

    for i in choice:
        vote_info.append({i.choice_text:i.votes})

    return JsonResponse(vote_info, safe=False)

vote/templates/vote/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    

    <title>Cat or Dog?{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <!-- my navbar -->
    {% include 'vote/nav_bar.html' %}
    <div class="container">
      <div class="row text-center">

        <div class="col-md-6 m-auto">
        {% block content %} {% endblock content %}
        </div>
      </div>
    </div>



    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>


  </body>
</html>

vote/templates/vote/home.html
{% extends "vote/base.html" %}
{% load static %}


{% block content %}
<link rel="stylesheet" text='text/css' href="{% static '/css/main.css' %}">

  <h2>Polls for Pet Friends.</h2>
  {% if questions %}
    {% for question in questions %}
      <div class="card mb-2">
        <div class="card-body">
          <p class="lead">{{question.question_text}}
           <a class="btn btn-primary btn-sm" href="{% url "vote:vote" question.id %}" role='button'>Vote</a>
            <a class="btn btn-outline-primary btn-sm" href="{% url "vote:results" question.id %}" role='button'>Results</a>
          </p>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>No polls available at this time.</p>
  {% endif %}
{% endblock content %}

vote/templates/vote/nav_bar.html
{% load static %}
<nav class="navbar navbar-dark bg-primary mb-4">
  <div class="container-fluid">
    <div class="mx-auto">
      <a class="navbar-brand" href="/">🐱 Cat or Dog? 🐶</a>
    </div>
  </div>
</nav>

vote/templates/vote/results.html
{% extends 'vote/base.html' %}

{% block content %}

<!--info so I could use Zing Chart -->
<script src="https://cdn.zingchart.com/zingchart.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <h3 class="text-center mb-3">{{ question.question_text }}</h3>

  <ul class="list-group mb-4">

    {% for choice in question.choice_set.all %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        {{ choice.choice_text }} <span class="badge bg-success rounded-pill ">{{ choice.votes }}</span>
      </li>
    {% endfor %}
  </ul>

  <a class="btn btn-success" href="{% url 'vote:vote' question.id %}">Vote again?</a>
  <a class="btn btn-secondary" href="{% url "vote:home" %}" role='button'>Back to Questions</a>

<div id="myChart"></div>

<script>

  var state ={
    "items":[],
    "values":[],
  }

  var objId = "{{question.id}}"

	var dataURL = `/resultsdata/${objId}/`
  $.ajax({
    method: 'GET',
    url:dataURL,
    success: function(response){
      console.log("Response:", response)
      for (var i in response){

        var key = Object.keys(response[i])[0]
        var value = Object.values(response[i])[0]

        state.items.push(key)
        state.values.push(value)
      }
      console.log('STATE:', state)
      buildChart()
    }
  })

  function buildChart(){

    var chartData = {
      "type": "bar",
      "scale-x":{
        "values":state.items
      },
      "series":[
        {
          "values":state.values
        }
      ]
    }

    zingchart.render({
      id: 'myChart',
      data: chartData,
    });
  }

</script>

{% endblock content %}

vote/templates/vote/vote.html
{% extends 'vote/base.html' %}
{% load static %}



{% block content %}
<link rel="stylesheet" text='text/css' href="{% static '/css/main.css' %}">

{% if error_message %}
<p class="alert alert-danger"><strong>{{ error_message }}</strong></p>
{% endif %}

<a class="btn btn-secondary btn-sm" href="{% url "vote:home" %}" role='button'>Back to Questions</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>


  <form action="{% url 'vote:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id= "choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <br>
  {% endfor %}
  <div class="d-grid gap-2 col-6 mx-auto">
    <input type="submit" value="Vote" class="btn btn-success">
  </div>
  </form>


{% endblock content %}